# For details of what checks are run for PRs please refer below
# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Docker CI

on: 
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERISON: "3.10"
  POETRY_VERSION: "1.1.11"

jobs:
  test:
    name: Build and test docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKER_TAG: 'cdx-python-testing:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}'
    steps:
      - name: Checkout code
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup python ${{ env.PYTHON_VERISON }}
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERISON }}
      - name: Install poetry
        # see https://github.com/marketplace/actions/setup-poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Poetry build
        run: poetry build
      - name: get version
        run: poetry version -s

      - name: Build Docker image
        run: |
          VERSION=`poetry version -s`
          docker build -f Dockerfile --build-arg "VERSION=$VERSION" -t "$DOCKER_TAG" .
      - name: Test Docker image
        run: docker run --rm "$DOCKER_TAG" -h
      - name: Destroy Docker image
        # run regardless of outcome
        if: ${{ always() }}
        run: docker rmi -f "$DOCKER_TAG"
