name: Manual Pre Release Publish

on:
  workflow_dispatch:

env:
  REPORTS_DIR: CI_reports
  DIST_DIR: dist
  DIST_ARTIFACT: python-dist
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.1.15"

jobs:
  release_candidate:
    runs-on: ubuntu-latest
    concurrency: release_candidate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: 'x64'

      - name: Install poetry
        # see https://github.com/marketplace/actions/setup-poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install poetry=="$POETRY_VERSION" --upgrade pip
          poetry config virtualenvs.create false
          poetry install

      - name: Install dependencies
        run: poetry install --no-root

      - name: View poetry version
        run: poetry --version

      - name: Perform Release 📦
        run: semantic-release publish --prerelease
        env:
          GH_TOKEN:            ${{ secrets.GH_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
